//
//  HomePresenter.swift
//  brain-trainning
//
//  Created by 宮地麻央 on 2018/12/04.
//  Copyright (c) 2018年 mao.miyaji. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
}
