//
//  HomeRouter.swift
//  brain-trainning
//
//  Created by mao.miyaji on 2018/12/04.
//  Copyright (c) 2018年 mao.miyaji. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic
{
    func routeToTrainingList(segue: UIStoryboardSegue?)
}

protocol HomeDataPassing
{
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing

    func routeToTrainingList(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! TrainingListViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToTrainingList(source: dataStore!, destination: &destinationDS)
        } else {
            let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "TrainingListViewController") as! TrainingListViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToTrainingList(source: dataStore!, destination: &destinationDS)
            navigateToTrainingList(source: viewController!, destination: destinationVC)
        }
    }

    // MARK: Navigation
    
    func navigateToTrainingList(source: HomeViewController, destination: TrainingListViewController)
    {
        // Loading表示するために遅延処理
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 3) {
            source.show(destination, sender: nil)
        }
    }

    // MARK: Passing data
    
    func passDataToTrainingList(source: HomeDataStore, destination: inout TrainingListDataStore)
    {
        // pass data to destination
    }
}
