//
//  TrainingListPresenter.swift
//  brain-trainning
//
//  Created by mao.miyaji on 2019/01/18.
//  Copyright (c) 2019年 mao.miyaji. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TrainingListPresentationLogic
{
}

class TrainingListPresenter: TrainingListPresentationLogic
{
    weak var viewController: TrainingListDisplayLogic?
}
