//
//  TitlePresenter.swift
//  brain-trainning
//
//  Created by mao.miyaji on 2018/11/30.
//  Copyright (c) 2018年 mao.miyaji. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TitlePresentationLogic
{
}

class TitlePresenter: TitlePresentationLogic
{
    weak var viewController: TitleDisplayLogic?
}
