//
//  TitleRouter.swift
//  brain-trainning
//
//  Created by mao.miyaji on 2018/11/30.
//  Copyright (c) 2018年 mao.miyaji. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TitleRoutingLogic
{
    func routeToHome(segue: UIStoryboardSegue?)
}

protocol TitleDataPassing
{
    var dataStore: TitleDataStore? { get }
}

class TitleRouter: NSObject, TitleRoutingLogic, TitleDataPassing
{
    weak var viewController: TitleViewController?
    var dataStore: TitleDataStore?
    
    // MARK: Routing
    
    func routeToHome(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! HomeViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToHome(source: dataStore!, destination: &destinationDS)
        } else {
            let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "HomeViewController") as! HomeViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToHome(source: dataStore!, destination: &destinationDS)
            navigateToHome(source: viewController!, destination: destinationVC)
        }
    }

    // MARK: Navigation
    
    func navigateToHome(source: TitleViewController, destination: HomeViewController)
    {
        // Loading表示するために遅延処理
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 3) {
            source.show(destination, sender: nil)
        }
    }
    
    // MARK: Passing data
    
    func passDataToHome(source: TitleDataStore, destination: inout HomeDataStore)
    {
        // pass data to destination
    }
}
